### ISSUE TITLE
Error: Filename too long

### ISSUE THREAD

**Issue by Menno-van-Dam** [GeoscienceAustralia/ptha#28]
Hello,

I am trying to download your code using GitHub Desktop, but I keep running into an error related to overly long file names: 

Cloning into 'C:\ptha'...
remote: Enumerating objects: 28162, done.        
remote: Counting objects: 100% (2758/2758), done.        
remote: Compressing objects: 100% (1388/1388), done.        
remote: Total 28162 (delta 1478), reused 2515 (delta 1318), pack-reused 25404        
Receiving objects: 100% (28162/28162), 156.85 MiB | 8.65 MiB/s, done.
Resolving deltas: 100% (18246/18246), done.
error: unable to create file misc/probabilistic_inundation_tonga2020/swals/plots/historic_events_time_series_plots/Chile2010/nukualofa_gauge_modelVdata_Chile2010_validation_PTHA18_HS_128607_source-risetime_0-ambientsealevel_0.0-full-linear_with_manning-0.035-highres_tonga-RUN_20201130_172631113.png: Filename too long
error: unable to create file misc/probabilistic_inundation_tonga2020/swals/plots/historic_events_time_series_plots/Chile2015/nukualofa_gauge_modelVdata_Chile2015_validation_Williamson_source_inversion-risetime_0-ambientsealevel_0.0-full-linear_with_manning-0.035-highres_tonga-RUN_20201130_172630123.png: Filename too long
error: unable to create file misc/probabilistic_inundation_tonga2020/swals/plots/historic_events_time_series_plots/Tohoku2011/nukualofa_gauge_modelVdata_Tohoku2011_validation_PTHA18_HS_46994-risetime_0-ambientsealevel_0.0-full-linear_with_manning-0.035-highres_tonga-RUN_20201130_172740486.png: Filename too long
error: unable to create file misc/probabilistic_inundation_tonga2020/swals/plots/historic_events_time_series_plots/Tonga2006/nukualofa_gauge_modelVdata_Tonga2006_validation_PTHA18_VAUS_26849_load_balance-risetime_0-ambientsealevel_0.0-full-linear_with_manning-0.035-highres_tonga-RUN_20201130_172740871.png: Filename too long
Updating files: 100% (2260/2260), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

It appears that a couple of the png files included in your package have names that are too long for windows to process. I've tried downloading the package directly to the C drive, with no subfolders, but the path name is still too long. Downloading the files as a zip doesn't work either, presumably due to the same issue:

![image](https://github.com/GeoscienceAustralia/ptha/assets/146923537/0fb9636f-e5d1-46ee-b651-096aaa868965)

Could you adjust the filename of the pngs to something shorter? I am unable to download all of your files as it stands.

Thanks in advance,

**Comment by gareth-d-ga** [comment]
Done -- can you clone master now?

**Comment by Menno-van-Dam** [comment]
Unfortunately the error persists:

Cloning into 'C:\Users\Dam_mo\OneDrive - Stichting Deltares\Documents\Repos\ptha'...
remote: Enumerating objects: 28342, done.        
remote: Counting objects: 100% (2938/2938), done.        
remote: Compressing objects: 100% (1344/1344), done.        
remote: Total 28342 (delta 1591), reused 2742 (delta 1542), pack-reused 25404        
Receiving objects: 100% (28342/28342), 156.90 MiB | 18.26 MiB/s, done.
Resolving deltas: 100% (18359/18359), done.
error: unable to create file misc/SW_WA_2021_2024/greater_perth_revised2023/analysis/probabilistic_inundation/run_compute_exceedance_rates_at_epistemic_uncertainty_VARIABLE_SOURCEZONE_PERCENTILE_LOWER_UPPER_EXCEEDANCETHRESHOLD.sh: Filename too long
error: unable to create file ptha_access/example_event_access_scripts/multi_site_scenario_selection/batch_plots_SRC_kermadectonga2_SLP_variable_uniform_CRV_rate_median_EXRATE_4e-04_STGTOL_0.1_NGAUGE_3/initial_condition_DESIRED_EVENT_ROW_28628.png: Filename too long
error: unable to create file ptha_access/example_event_access_scripts/multi_site_scenario_selection/batch_plots_SRC_kermadectonga2_SLP_variable_uniform_CRV_rate_median_EXRATE_4e-04_STGTOL_0.1_NGAUGE_3/tsunami_gauges_DESIRED_EVENT_ROW_28628.png: Filename too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'


Would you like to retry cloning ?

**Comment by Menno-van-Dam** [comment]
It works now, but only if I place it directly in the C drive with no subfolders. However the filenames are still very long, which could likely lead to problems with other users. Once I place it in the documents folder for example, I again receive the error related to long file names.

**Comment by gareth-d-ga** [comment]
Thanks for the update. Glad you got it working. I agree it could cause problems so I'll leave this issue open for now.

**Comment by gareth-d-ga** [comment]
This link may show another workaround: https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

**Comment by gareth-d-ga** [comment]
Another possible workaround is to use the [7-zip program](https://www.7-zip.org/) to unzip the files. It seems able to work with relatively long file paths (where other zip programs fail on Windows) and supports regular `.zip` as well as other formats
